### ISSUE TITLE
What is a tail ?

### ISSUE THREAD

**Issue by devictr** [ikawaha/mast#10]
Hello,

Your code has been really helpful to me and I thank you very much.
I have to use the MAST algorithm for a school project, but I have to implement it in Java.

I am having trouble understanding what is the Tail attribute in your State structure. Could you help me out ?
Thanks

**Comment by ikawaha** [comment]
![image](https://cloud.githubusercontent.com/assets/4232165/8250504/7478f8ae-16af-11e5-95fa-bb12e679bb7e.png)

FYI:
There is a bug in string to string transduser implementation.
I fixed same problem in string to int version.
https://github.com/ikawaha/mast/commit/163b254fc58bedeb51c77ccf1c567798ee11ed87

**Comment by devictr** [comment]
Thank you so much.
I would be glad to give you a hand on the bugfix, but Golang is still very new to me. I hope sometime I will be able to get involved
